const mongoose = require('mongoose');

const PlaylistSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  description: {
    type: String,
    default: 'Playlist generated by TSTimer.'
  },
  tracks: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Track'
    }
  ],
  visit: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Visit'
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  requestedDuration: {
    type: Number,
    required: true // En segundos
  },
  actualDuration: {
    type: Number // En segundos
  },
  saveCount: {
    type: Number,
    default: 0
  }
});

module.exports = mongoose.model('Playlist', PlaylistSchema);
